
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli-browsers
    steps:
      - checkout
      - run: composer install
      - run: composer test
      - run: cat docs/coverage/coverage.txt
      - run: ./coverage.php
      - store_artifacts:
          path: docs/coverage/coverage.txt
          destination: coverage.txt
