# machine:
#   php:
#     version: 5.6.22

# dependencies:
#   pre:
#     - apt-get install jq

# test:
#   override:
#     - composer test
#   post:
#     - cat docs/coverage/coverage.txt
#     - ./coverage.php
#     - cp docs/coverage/coverage.txt $CIRCLE_ARTIFACTS

version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-cli-browsers
    steps:
      - checkout
      - run: composer install
  test:
    docker:
      - image: circleci/php:7.0-cli-browsers
    steps:
      - run: composer test
workflows:
  version: 2
  go:
    jobs:
      - build
      - test
